version: "3.8"
services:
  clients_app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - mysql
    networks:
      - app_network

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - clients_app
    environment:
      NGINX_FPM_HOST: clients_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  mysql:
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: client-app
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: root
      MYSQL_PASSWORD:
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
